### ISSUE TITLE
INMET changed the API silently

### ISSUE THREAD

**Issue by juliohm** [JuliaClimate/INMET.jl#3]
Apparently something changed in the INMET side that broke our functions.

**Comment by ProfLeao** [comment]
Have all the features stopped working?

**Comment by juliohm** [comment]
The `stations` function works still. The link that used to hold the manual
now points to a page with a contact email, which is hard to believe given
that this is a public website/service by the brazilian governament.

Em sex., 6 de out. de 2023 18:22, Reginaldo Gonçalves Leão Junior <
***@***.***> escreveu:

**Comment by ProfLeao** [comment]
I understand.  If you need I can try to help.  The package is important for a tool I'm developing.  However, I will only have availability in about 10 days.

**Comment by juliohm** [comment]
Any help is appreciated. I feel that this issue will require contact with
INMET.

Em sex., 6 de out. de 2023 23:38, Reginaldo Gonçalves Leão Junior <
***@***.***> escreveu:

**Comment by ProfLeao** [comment]
@eliascarv say me that he already sent the email to INMET. Elias, can you keep us updated ?

**Comment by eliascarv** [comment]
Of course

**Comment by ProfLeao** [comment]
Any news from INMET?

**Comment by eliascarv** [comment]
Unfortunately, we have not yet received a response from INMET.

**Comment by eliascarv** [comment]
However, we continue trying to contact INMET. I will send any updates here.

**Comment by eliascarv** [comment]
Unfortunately, even after two weeks, we have not received a response from INMET.

**Comment by juliohm** [comment]
@ProfLeao I fixed the issue. The INMET API now requires a token, which you can request by sending an email to cadastro.act@inmet.gov.br
